### PLAIN TEXT

# curl -X GET http://localhost:8080/hello
GET http://localhost:8080/hello
Accept: text/plain

### HTML

GET http://localhost:8080/hello
Accept: text/html

### XML

GET http://localhost:8080/hello
Accept: application/xml

### JSON

GET http://localhost:8080/hello
Accept: application/json

###