# curl -X GET http://localhost:8080/hello
GET http://localhost:8080/hello
Accept: text/plain

###

GET http://localhost:8080/hello
Accept: text/html

###

GET http://localhost:8080/hello
Accept: application/xml

###

GET http://localhost:8080/hello
Accept: application/json

###